### PR TITLE
Migration: OpenCortext -> Neurmllite for GLIF cells

### PR DESCRIPTION
**Pull request by anujanegi**
Started migrating the code to neuromllite. For the test model (566291893), these are the generated files from parse_glif.py:

**TEST_566291893.net.nml**
```
<neuroml xmlns="http://www.neuroml.org/schema/neuroml2"  xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.neuroml.org/schema/neuroml2 https://raw.github.com/NeuroML/NeuroML2/development/Schemas/NeuroML2/NeuroML_v2.3.xsd" id="TEST_566291893">
    <notes>Generated by NeuroMLlite v0.5.1
    Generated network: TEST_566291893
    Generation seed: 1234</notes>
    <include href="TEST_566291893__lems.xml"/>
    <pulseGenerator id="pg0" delay="100ms" duration="1000ms" amplitude="50 pA"/>
    <network id="TEST_566291893" type="networkWithTemperature" temperature="32.0degC">
        <notes>1 Leaky Integrate and Fire (LIF)_Sst-IRES-Cre;Ai14-165865.03.01.01</notes>
        <property tag="recommended_dt_ms" value="0.01"/>
        <property tag="recommended_duration_ms" value="1200.0"/>
        <population id="pop_566291893" component="GLIF_566291893" size="1"/>
        <inputList id="Stim0" population="pop_566291893" component="pg0"/>
    </network>
</neuroml>
```

**LEMS_Sim_test_566291893.xml**
```
<Lems>
    
    <!-- 

        This LEMS file has been automatically generated using PyNeuroML v0.7.1 (libNeuroML v0.4.0)

     -->
    
    <!-- Specify which component to run -->
    <Target component="Sim_test_566291893" reportFile="report.Sim_test_566291893.txt"/>

    <!-- Include core NeuroML2 ComponentType definitions -->
    <Include file="Cells.xml"/>
    <Include file="Networks.xml"/>
    <Include file="Simulation.xml"/>
    
    <Include file="PyNN.xml"/>
    <Include file="TEST_566291893.net.nml"/>
    <Include file="TEST_566291893__lems.xml"/>
   
    <Simulation id="Sim_test_566291893" length="1200.0ms" step="0.01ms" target="TEST_566291893" seed="5678">  <!-- Note seed: ensures same random numbers used every run -->
        
        <Display id="pop_566291893_v" title="Plots of pop_566291893_v" timeScale="1ms" xmin="-120.0" xmax="1320.0" ymin="-80" ymax="40">
            <Line id="pop_566291893_0__v" quantity="pop_566291893[0]/v" scale="1mV" color="#d54f33" timeScale="1ms"/>
        </Display>
        
        <OutputFile id="Sim_test_566291893_pop_566291893_v_dat" fileName="Sim_test_566291893.pop_566291893.v.dat">
            <OutputColumn id="pop_566291893_0__v" quantity="pop_566291893[0]/v"/> 
        </OutputFile>
        
    </Simulation>

</Lems>
```

### CODE REVIEW

**Comment by anujanegi** [comment]
See error on gh-actions.
I think, I need to include '../GLIFS.xml' in the LEMS_Sim_test_566291893.xml.
```
<Include file="../GLIFs.xml"/>
```
Coudn't find a nmllite example.py that does this explicitly. How do I fo this? @pgleeson

**Comment by anujanegi** [comment]
> See error on gh-actions. I think, I need to include '../GLIFS.xml' in the LEMS_Sim_test_566291893.xml.
> 
> ```
> <Include file="../GLIFs.xml"/>
> ```
> 
> Coudn't find a nmllite example.py that does this explicitly. How do I fo this? @pgleeson

Solved with a hacky fix!

**Comment by anujanegi** [comment]
@pgleeson How do I record threshold values, when simulating with nmllite?

Basically, what's the neuromllite equivalent for this:
https://github.com/OpenSourceBrain/AllenInstituteNeuroML/blob/c5857a19902ecc6cf0cbd68fe2c56efb616864b2/CellTypesDatabase/models/GLIF/parse_glif.py#L148-L155

**Comment by pgleeson** [comment]
@anujanegi See https://github.com/OpenSourceBrain/AllenInstituteNeuroML/commit/10abf28495bbbd7567491407da7d05e0e18f497f

**Comment by anujanegi** [comment]
@pgleeson This is ready for merge!

**Comment by pgleeson** [comment]
@anujanegi Some of the threshold figures seem to be missing from this commit..?
https://github.com/anujanegi/AllenInstituteNeuroML/blob/neurmllite/CellTypesDatabase/models/GLIF/566282032/README.md

**Comment by anujanegi** [comment]
> @anujanegi Some of the threshold figures seem to be missing from this commit..? https://github.com/anujanegi/AllenInstituteNeuroML/blob/neurmllite/CellTypesDatabase/models/GLIF/566282032/README.md

@pgleeson pushed!

**Comment by pgleeson** [comment]
Looks good.

**Pull request merged**
