### PR TITLE
Support for all active celltype

### PR DESCRIPTION
**Pull request by anujanegi**
Trying to make sense of this error message. What am I missing? @sanjayankur31 @pgleeson 

When I try to validate the generated .cell.nml:
``` 
jNeuroML >>  Validating: /home/anujanegi/tj/AllenInstituteNeuroML/CellTypesDatabase/models/NeuroML2/Cell_497233223.cell.nml
 jNeuroML >>  Valid against schema
 jNeuroML >>    Test: 10005 (Segment Group used in the include element of segmentGroup should exist) failed! ... SegmentGroup: soma_group, includes: soma
 jNeuroML >>    Test: 10006 (Segment Groups used in biophysicalProperties should exist) failed! ... ChannelDensity: pas_soma specifies: soma which doesn't exist
 jNeuroML >>    Test: 10006 (Segment Groups used in biophysicalProperties should exist) failed! ... ChannelDensity: pas_apic specifies: apic which doesn't exist
 jNeuroML >>    Test: 10006 (Segment Groups used in biophysicalProperties should exist) failed! ... ChannelDensity: NaV_soma specifies: soma which doesn't exist
 jNeuroML >>    Test: 10006 (Segment Groups used in biophysicalProperties should exist) failed! ... ChannelDensity: SK_soma specifies: soma which doesn't exist
 jNeuroML >>    Test: 10006 (Segment Groups used in biophysicalProperties should exist) failed! ... ChannelDensity: Kv3_1_soma specifies: soma which doesn't exist
 jNeuroML >>    Test: 10006 (Segment Groups used in biophysicalProperties should exist) failed! ... ChannelDensity: Ih_soma specifies: soma which doesn't exist
 jNeuroML >>    Test: 10006 (Segment Groups used in biophysicalProperties should exist) failed! ... ChannelDensity: NaV_apic specifies: apic which doesn't exist
 jNeuroML >>    Test: 10006 (Segment Groups used in biophysicalProperties should exist) failed! ... ChannelDensity: Kv3_1_apic specifies: apic which doesn't exist
 jNeuroML >>    Test: 10006 (Segment Groups used in biophysicalProperties should exist) failed! ... ChannelDensity: Im_v2_apic specifies: apic which doesn't exist
 jNeuroML >>    Test: 10006 (Segment Groups used in biophysicalProperties should exist) failed! ... ChannelDensity: Ih_apic specifies: apic which doesn't exist
 jNeuroML >>    Test: 10006 (Segment Groups used in biophysicalProperties should exist) failed! ... ChannelDensity: Ca_HVA_soma specifies: soma which doesn't exist
 jNeuroML >>    Test: 10006 (Segment Groups used in biophysicalProperties should exist) failed! ... ChannelDensity: Ca_LVA_soma specifies: soma which doesn't exist
```

### CODE REVIEW

**Review by anujanegi — COMMENTED** [review]
In the generated [cell.nml](https://github.com/OpenSourceBrain/AllenInstituteNeuroML/pull/27/files#diff-a425eef7c81ff86255ea573b8aabb0b8720e0c04e36f1d770238e03b80631f64) file, `<segmentGroup id="soma">` is missing, which might be the cause of this error.

But it doesn't look like anything needs to change in these lines for active cells. Am I missing something?
https://github.com/OpenSourceBrain/AllenInstituteNeuroML/blob/cea3c93107be1dfa6c164316dec123524d4c9af8/CellTypesDatabase/models/ParseAll.py#L134-L153

@sanjayankur31 @pgleeson

**Comment by pgleeson** [comment]
@anujanegi Testing this out in my branch here:https://github.com/OpenSourceBrain/AllenInstituteNeuroML/tree/pg_test. I've just realised that the script can't handle both all active and perisomatic in the one run... If you run with one type the other will fail...

**Comment by pgleeson** [comment]
@anujanegi The issue with generating the soma segment group is fixed in https://github.com/OpenSourceBrain/AllenInstituteNeuroML/commit/af1a0baeeee029a09bca7d5f9cd809eda55adaf8#diff-ea7fc52438018fb455633304804ded95b1bfbd3d88bb46345a6c4aaa7885c609 I believe...

Looking at another issue now with the group apic...

**Comment by pgleeson** [comment]
@anujanegi I've tested the latest changes with another all active cell on here: https://github.com/OpenSourceBrain/AllenInstituteNeuroML/tree/pg_another_all_active and it seems to work now. Let's discuss tomorrow.

**Comment by pgleeson** [comment]
Closing this @anujanegi as I assume all relevant changes are on the master branch now..?

**Pull request closed without merging**
