### PR TITLE
Model summary and tests!

### PR DESCRIPTION
**Pull request by anujanegi**

### CODE REVIEW

**Comment by anujanegi** [comment]
How to simulate a specific sweep run when running the LEMS models? @pgleeson @sanjayankur31

**Comment by pgleeson** [comment]
@anujanegi The specific sweep that's interesting (e.g. sweep 54) and the corresponding amplitude of the curent are picked by looking for a good stim in the ephys page (http://celltypes.brain-map.org/mouse/experiment/electrophysiology/486111903) which causes the original cell to spike as well as the model and these are set in the data helper:
https://github.com/OpenSourceBrain/AllenInstituteNeuroML/blob/c2c824399faa31ca8141c8747d0bf5872c7cd713/CellTypesDatabase/data/data_helper.py#L19-L24 

I've modified this file to be a bit more robust in my branch pg_test.

The issue I have now is that the new model is claiming to have an experiment id which is the same as the model id:
https://github.com/OpenSourceBrain/AllenInstituteNeuroML/blob/c2c824399faa31ca8141c8747d0bf5872c7cd713/CellTypesDatabase/models/497232312/metadata.json#L3
which it shouldn't be...

**Comment by anujanegi** [comment]
@pgleeson given #33 should I push 472450023 model as well, or leave it out for now?

**Comment by pgleeson** [comment]
All looks good now!

**Pull request merged**
