### PR TITLE
Neuron run tests for models

### PR DESCRIPTION
**Pull request by anujanegi**
Currently, only for the active cell 497232312 and the perisomatic cell 483108201, the spike times from NRN and LEMS match well enough (see tolerance). 

**483108201 (0.0142 tolerance):** 
LEMS_483108201

**497232312 (0.006 tolerance):**
LEMS_497232312

Spike times for **486556811** are a bit off towards the end (set high tolerance??). Currently, the tolerance is set to 0.1.
LEMS_486556811

```
[omv] Comparison of 
                    (observed data): [1046.48, 1088.265, 1163.83, 1256.89, 1348.585, 1437.3700000000001, 1523.79, 1608.2749999999999, 1691.16, 1772.7250000000001, 1853.1850000000002, 1932.72, 2011.4800000000002]
                    and
                    (expected data): [1046.4550000112365, 1089.5750000121777, 1168.7450000139058, 1264.3800000159933, 1357.6200000180286, 1447.7000000199948, 1535.2400000219056, 1620.7150000237714, 1704.4900000256, 1786.860000027398, 1868.0600000291704, 1948.2850000309215]
                    failed against tolerance 0.1
[omv]       Observable                        Test Passed     
[omv]       --------------------------------------------------
[omv]       spike times                            ✘          
[omv]       +++++++++++++++++++++ Error info ++++++++++++++++++
[omv]        Return code: 0
[omv]        Output:  jNeuroML v0.11.1
```

Spike times for **472450023** are completely off. 
LEMS_472450023

```
[omv] Comparison of 
                    (observed data): [1042.215, 1086.965, 1136.99, 1188.215, 1240.03, 1292.3700000000001, 1345.22, 1398.58, 1452.44, 1506.8049999999998, 1561.6699999999998, 1617.03, 1672.885, 1729.2350000000001, 1786.07, 1843.39, 1901.2, 1959.49, 2018.2549999999999]
                    and
                    (expected data): [1040.3600000111035, 1074.0300000118384, 1111.4750000126558, 1150.2200000135015, 1189.5250000143594, 1229.2800000152272, 1269.4700000161044, 1310.090000016991, 1351.1400000178871, 1392.6250000187927, 1434.5400000197076, 1476.890000020632, 1519.685000021566, 1562.9200000225098, 1606.6000000234633, 1650.7350000244267, 1695.3200000253998, 1740.365000026383, 1785.8700000273764, 1831.8400000283798, 1878.2750000293934, 1925.1900000304174, 1972.5750000314517, 2020.4850000324975]
                    failed against tolerance 0.1
[omv]       Observable                        Test Passed     
[omv]       --------------------------------------------------
[omv]       spike times                            ✘          
[omv]       +++++++++++++++++++++ Error info ++++++++++++++++++
[omv]        Return code: 0
[omv]        Output:  jNeuroML v0.11.1
```

Further investigation is needed. Test cases for these fail as shown above as tolerance is set to low currently.

@pgleeson @sanjayankur31

### CODE REVIEW

**Comment by anujanegi** [comment]
Updated to a less spiking sweep (51 now) and updated tests accordingly for model **486556811**. Test passes with 0.009 tolerance.
LEMS_486556811

**Comment by anujanegi** [comment]
Updated to a different sweep (picked 28 for now) and updated tests accordingly for model **472450023**. Test passes with 0.014603912968289823 tolerance.

LEMS_472450023


_P.S. Sweep 28 only has 3 spikes, but all other sweeps are either a bad match to the cell response or have way too many spikes to be a good test sweep._

**Comment by pgleeson** [comment]
FYI @anujanegi adding this option will ensure all tests run, regardless of the order:
https://github.com/OpenSourceBrain/osb-model-validation/blob/b1784d1d63bbdacf0e2b746d62bad1a164efd074/.github/workflows/ci.yml#L16

**Comment by anujanegi** [comment]
I changed the neuron version to NEURON 8.0.0.
We have some tolerance discrepancies for files in the NEURON folder.
What do you suggest?
@pgleeson

**Comment by pgleeson** [comment]
@anujanegi Probably this can be closed, as most of the changes are on master now. 

We can use the https://github.com/OpenSourceBrain/AllenInstituteNeuroML/tree/pg_test_nrn branch to test multiple versions of Neuron, but probably best to trace the issue first back to whether this is a problem with the Hay et al model...

**Pull request closed without merging**
